version: "3.8"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      DB_NAME: app
      DB_PASS: development
      DB_USER: developer
      DB_HOST: db
    container_name: "socialnetwork"
    volumes:
      - ./source:/home/user/app

  db:
    image: postgres:alpine
    container_name: "socialnetwork_db"
    environment:
      POSTGRES_DATABASE: app
      POSTGRES_PASSWORD: development
      POSTGRES_USER: developer
    ports:
      - "8001:5432"

networks:
  net:
    name: socialnetwork_net
